name: Javascript Linter

on: [push, pull_request]

jobs: 
  lint:
    runs-on: ubuntu-tatest

    steps:
      - name : Install NodeJS
        uses: actions/setup-node@v6.1.0 
        with: 
          node-version: '18'
      - name: checkout
        uses: actions/checkout@v6.0.1
      - name : Eslint
        run: npm run lint
