name: Javascript Linter

on: [push, pull_request]

jobs: 
  lint:
    runs-on: ubuntu-tatest

    steps:
      - name : Install NodeJS
        uses: actions/setup-node@v6.1.0 
        with: 
          node-version: '18'
      - name: checkout
        uses: actions/checkout@v6.0.1
      - name : Install dependancies
        run: npm ci
      - name : Eslint
        run: npm run lint
  deploy:
    runs-on: ubuntu-tatest
    needs: [lint]
    if: github.ref == 'refs/heads/master'
  
    steps:
        - name: checkout
          uses: actions/checkout@v6.0.1
  
        - name: Copy SSH keys
          run: |
            mkdir -p ~/.ssh/
            echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/id_ed25519
            echo "${{ secrets.SSH_PUBLIC_KEY }}" >>  ~/.ssh/id_ed25519.pub
            chmod 600 ~/.ssh/id_ed25519
            ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
  
        - name: Deploy on SSH
          run: |
            ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir salut"
